# -- Autostart -- #

# Waybar
exec-once = bash /home/1nflutorm/.config/waybar/scripts/launch.sh

# Wallpaper
exec-once = awww-daemon

# Privilege escalation
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Auto-mount removable storage
exec-once = udiskie

# Idling
#exec-once = hypridle

# Notification center
exec-once = swaync

# Cursor
exec-once = hyprctl setcursor macOS 24
exec-once = hyprctl keyword input:kb_layout "us,ru"
exec-once = hyprctl keyword input:kb_options "grp:win_space_toggle"
